# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Robiul Islam
tagline:          'A Jekyll theme'
description:      'Ph.D. student at <a href="https://innopolis.university/en/" target="_blank">Innopolis University</a> . Alumni of 
<a href="https://www.hse.ru/en/" target="_blank">Higher School of Economics</a>, <a href="https://www.iutoic-dhaka.edu/" target="_blank">Islamic University of Technology</a>, <a href="https://www.ewubd.edu/" target="_blank"> East West University</a>.'
url:              http://hyde.getpoole.com
baseurl:          /newversion/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

theme: jekyll-theme-leap-day
